# GitLab Dark Grey Theme for Kitty

background            #222222
foreground            #ffffff
selection_background  #ffffff
selection_foreground  #222222

cursor                #ffffff
cursor_text_color     #bfbfbf

# The 16 terminal colors

# black
color0 #000000
color8 #666666

# red
color1 #f57f6c
color9 #fcb5aa

# green
color2  #52b87a
color10 #91d4a8

# yellow
color3  #d99530
color11 #e9be74

# blue
color4  #7fb6ed
color12 #498dd1

# magenta
color5  #f88aaf
color13 #fcacc5

# cyan
color6  #32c5d2
color14 #5edee3

# white
color7  #ffffff
color15 #ffffff
